<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE system [
<!ELEMENT system (method+)>
<!ELEMENT method (#PCDATA)>
<!ATTLIST method name CDATA "">
]>
<system>
	<method name="createAccountTable"><![CDATA[
CREATE TABLE IF NOT EXISTS DEBS.ACCOUNT (
 ID IDENTITY GENERATED ALWAYS AS IDENTITY,
 CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
 BALANCE DECIMAL NOT NULL DEFAULT(0.00),
 DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
 NAME VARCHAR(50) UNIQUE NOT NULL,
 DESCRIPTION VARCHAR(255) NOT NULL,
 PARENT_ID BIGINT NOT NULL,
 ACCOUNT_TYPE INT NOT NULL)
	]]></method>
	<method name="createEntryTable"><![CDATA[
CREATE TABLE IF NOT EXISTS DEBS.ENTRY (
 ID IDENTITY GENERATED ALWAYS AS IDENTITY,
 CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
 DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
 AMOUNT DECIMAL NOT NULL DEFAULT(0.00),
 ETYPE INT CHECK(ETYPE >= 1 AND ETYPE <= 2),
 ACCOUNT_ID BIGINT NOT NULL CHECK(ACCOUNT_ID > 0),
 CLEARED BOOLEAN NOT NULL DEFAULT(FALSE),
 CLEARED_TS SMALLDATETIME NOT NULL,
 FOREIGN KEY(ACCOUNT_ID) REFERENCES DEBS.ACCOUNT(ID))
	]]></method>
	<method name="createTransactionTable"><![CDATA[
CREATE TABLE IF NOT EXISTS DEBS.TRANSACTION (
 ID IDENTITY GENERATED ALWAYS AS IDENTITY,
 CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
 DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
 TDATE DATE NOT NULL,
 REFERENCE VARCHAR(255) NOT NULL,
 NARRATIVE VARCHAR(255) NOT NULL,
 EID_FROM BIGINT NOT NULL,
 EID_TO BIGINT NOT NULL,
 CHECK(EID_FROM > 0),
 CHECK(EID_TO > 0),
 CHECK(EID_FROM != EID_TO),
 FOREIGN KEY(EID_FROM) REFERENCES DEBS.ENTRY(ID),
 FOREIGN KEY(EID_TO) REFERENCES DEBS.ENTRY(ID))
	]]></method>
	<method name="createEmployeeTable"><![CDATA[
CREATE TABLE IF NOT EXISTS DEBS.EMPLOYEE (
 ID IDENTITY GENERATED ALWAYS AS IDENTITY,
 CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
 DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
 FULLNAME VARCHAR(100) NOT NULL,
 CONTACT_NUMBER VARCHAR(12) NOT NULL,
 NID VARCHAR(30) NOT NULL UNIQUE)
	]]></method>
	<method name="createPayrunTable">
CREATE TABLE IF NOT EXISTS DEBS.PAYRUN (
 ID IDENTITY GENERATED ALWAYS AS IDENTITY,
 CREATED SMALLDATETIME NOT NULL DEFAULT(CURRENT_TIMESTAMP()),
 DELETED BOOLEAN NOT NULL DEFAULT(FALSE),
 EMPLOYEE_ID BIGINT NOT NULL,
 TDATE DATE NOT NULL,
 REFERENCE VARCHAR(255) NOT NULL,
 GROSS DECIMAL NOT NULL DEFAULT(0.00),
 TAX DECIMAL NOT NULL DEFAULT(0.00),
 NET DECIMAL NOT NULL DEFAULT(0.00),
 FOREIGN KEY(EMPLOYEE_ID) REFERENCES DEBS.EMPLOYEE(ID))
	</method>
</system>
