<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE system [
<!ELEMENT system (method+)>
<!ELEMENT method (#PCDATA)>
<!ATTLIST method name CDATA "">
]>
<system>
	<method name="createAccount"><![CDATA[
INSERT INTO DEBS.ACCOUNT(NAME,DESCRIPTION,PARENT_ID,ACCOUNT_TYPE) VALUES(?,?,?,?)
	]]></method>
	<method name="updateAccount"><![CDATA[
UPDATE DEBS.ACCOUNT SET NAME=?,DESCRIPTION=?,PARENT_ID=?,ACCOUNT_TYPE=? WHERE ID=?
	]]></method>
	<method name="updateAccountBalance"><![CDATA[
UPDATE DEBS.ACCOUNT SET BALANCE=? WHERE ID=?
	]]></method>
	<method name="deleteAccount"><![CDATA[
UPDATE DEBS.ACCOUNT SET DELETED=TRUE WHERE ID=?
	]]></method>
	<method name="getAccountById"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE ID=?
	]]></method>
	<method name="getAccountByName"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE NAME=?
	]]></method>
	<method name="getAllAccountsIncludeDeleted"><![CDATA[
SELECT * FROM DEBS.ACCOUNT
	]]></method>
	<method name="getAllAccounts"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE DELETED=FALSE
	]]></method>
	<method name="getGroupAccountsIncludeDeleted"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE ACCOUNT_TYPE=8
	]]></method>
	<method name="getGroupAccounts"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE ACCOUNT_TYPE=8 AND DELETED=FALSE
	]]></method>
	<method name="getActualAccountsIncludeDeleted"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE ACCOUNT_TYPE!=8
	]]></method>
	<method name="getActualAccounts"><![CDATA[
SELECT * FROM DEBS.ACCOUNT WHERE ACCOUNT_TYPE!=8 AND DELETED=FALSE
	]]></method>
	<method name="createTransactionEntry"><![CDATA[
INSERT INTO DEBS.ENTRY(AMOUNT,ETYPE,ACCOUNT_ID,CLEARED) VALUES(?,?,?,?)
	]]></method>
	<method name="createTransaction"><![CDATA[
INSERT INTO DEBS.TRANSACTION(REFERENCE,NARRATIVE,EID_FROM,EID_TO) VALUES(?,?,?,?)
	]]></method>
	<method name="getTransactionById"><![CDATA[
SELECT TX.ID,TX.CREATED,TX.DELETED,TX.REFERENCE,TX.NARRATIVE,
FE.ID AS "FROM_ID",FE.AMOUNT AS "FROM_AMOUNT",FE.ETYPE AS "FROM_ETYPE",FE.ACCOUNT_ID AS "FROM_ACCOUNT_ID",
TE.ID AS "TO_ID",TE.AMOUNT AS "TO_AMOUNT",TE.ETYPE AS "TO_ETYPE",TE.ACCOUNT_ID AS "TO_ACCOUNT_ID"
 FROM DEBS.TRANSACTION AS TX
 INNER JOIN DEBS.ENTRY AS FE ON FE.ID=TX.EID_FROM AND FE.ETYPE=1
 INNER JOIN DEBS.ENTRY AS TE ON TE.ID=TX.EID_TO AND TE.ETYPE=2
 WHERE TX.ID=?
	]]></method>
</system>
